/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/4D JUVER.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1_ARD-geom"].geometry}
        material={materials._1_ARD_front}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1_ARD-geom_1"].geometry}
        material={materials._1_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["_1_ARD-geom_2"].geometry}
        material={materials._1_ARD_edge}
      />
    </group>
  );
}

useGLTF.preload("/4D JUVER.gltf");
